server:
  port: 5000

endpoints:
  existing-api:
    url: ${endpoints.existing-api.given-url:${endpoints.existing-api.formed-url}}
    formed-url: ${endpoints.existing-api.base-path}:${endpoints.existing-api.port}
    given-url: http://localhost:3001
    base-path: http://localhost
    port: 3001