server:
  port: 5000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create

endpoints:
  existingApi:
    url: ${endpoints.existingApi.givenUrl:${endpoints.existingApi.formedUrl}}
    formedUrl: ${endpoints.existingApi.basePath}:${endpoints.existingApi.port}
    givenUrl: http://localhost:3001
    basePath: http://localhost
    port: 3001